### PR TITLE
feat(sourceMap): Make source-mapping of multi-files component working…

### PR DESCRIPTION
**Pull request by csailly**
PR for issue #36 Code coverage doesn't work on files linked with "src="

### CODE REVIEW

**Comment by eddyerburgh** [comment]
This is awesome, thanks so much 🙂

**Comment by Toilal** [comment]
It still doesn't work with `lang="ts"` (TypeScript)

**Comment by dinvlad** [comment]
Hmm, it works if I set
```ts
<script lang="ts">
  export { default } from './component';
</script>
```
but not if I use
```ts
<script src="./component.ts"></script>
```
Could this be improved to include the second use case?

**Comment by eddyerburgh** [comment]
@dinvlad could you please open an issue. Then I can keep track of the bug and look into fixing it

**Pull request merged**
